# Import your page classes (they must be defined in their own files)
from pages.home import HomePage
from pages.developers import DevelopersPage
from pages.contact import ContactPage
from pages.support import SuportPage
from pages.abtus import AbtusPage

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(919, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.icons_only_widget = QtWidgets.QWidget(self.centralwidget)
        self.icons_only_widget.setGeometry(QtCore.QRect(20, 10, 51, 541))
        self.icons_only_widget.setObjectName("icons_only_widget")
        self.label = QtWidgets.QLabel(self.icons_only_widget)
        self.label.setGeometry(QtCore.QRect(-10, 0, 70, 70))
        self.label.setMinimumSize(QtCore.QSize(70, 70))
        self.label.setMaximumSize(QtCore.QSize(70, 70))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/icons/resources/iStock-471629610-Converted.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(self.icons_only_widget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 70, 61, 451))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.home_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.home_btn.setMinimumSize(QtCore.QSize(50, 50))
        self.home_btn.setMaximumSize(QtCore.QSize(50, 50))
        self.home_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/resources/house-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/icons/resources/house-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.home_btn.setIcon(icon)
        self.home_btn.setIconSize(QtCore.QSize(20, 20))
        self.home_btn.setCheckable(True)
        self.home_btn.setAutoExclusive(True)
        self.home_btn.setObjectName("home_btn")
        self.verticalLayout.addWidget(self.home_btn)
        self.developers_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.developers_btn.setMinimumSize(QtCore.QSize(50, 50))
        self.developers_btn.setMaximumSize(QtCore.QSize(50, 50))
        self.developers_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/resources/group-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.developers_btn.setIcon(icon1)
        self.developers_btn.setIconSize(QtCore.QSize(20, 20))
        self.developers_btn.setCheckable(True)
        self.developers_btn.setAutoExclusive(True)
        self.developers_btn.setObjectName("developers_btn")
        self.verticalLayout.addWidget(self.developers_btn)
        self.contact_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.contact_btn.setMinimumSize(QtCore.QSize(50, 50))
        self.contact_btn.setMaximumSize(QtCore.QSize(50, 50))
        self.contact_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/resources/contacts-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.contact_btn.setIcon(icon2)
        self.contact_btn.setIconSize(QtCore.QSize(20, 20))
        self.contact_btn.setCheckable(True)
        self.contact_btn.setAutoExclusive(True)
        self.contact_btn.setObjectName("contact_btn")
        self.verticalLayout.addWidget(self.contact_btn)
        self.support_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.support_btn.setMinimumSize(QtCore.QSize(50, 50))
        self.support_btn.setMaximumSize(QtCore.QSize(50, 50))
        self.support_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/resources/support-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.support_btn.setIcon(icon3)
        self.support_btn.setIconSize(QtCore.QSize(20, 20))
        self.support_btn.setCheckable(True)
        self.support_btn.setAutoExclusive(True)
        self.support_btn.setObjectName("support_btn")
        self.verticalLayout.addWidget(self.support_btn)
        self.abtus_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.abtus_btn.setMinimumSize(QtCore.QSize(50, 50))
        self.abtus_btn.setMaximumSize(QtCore.QSize(50, 50))
        self.abtus_btn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/resources/clinic-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.abtus_btn.setIcon(icon4)
        self.abtus_btn.setIconSize(QtCore.QSize(20, 20))
        self.abtus_btn.setCheckable(True)
        self.abtus_btn.setAutoExclusive(True)
        self.abtus_btn.setObjectName("abtus_btn")
        self.verticalLayout.addWidget(self.abtus_btn)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.exit_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.exit_btn.setMinimumSize(QtCore.QSize(50, 50))
        self.exit_btn.setMaximumSize(QtCore.QSize(50, 50))
        self.exit_btn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/resources/x-mark-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit_btn.setIcon(icon5)
        self.exit_btn.setIconSize(QtCore.QSize(20, 20))
        self.exit_btn.setCheckable(True)
        self.exit_btn.setAutoExclusive(True)
        self.exit_btn.setObjectName("exit_btn")
        self.verticalLayout.addWidget(self.exit_btn)
        self.keys_only_widget = QtWidgets.QWidget(self.centralwidget)
        self.keys_only_widget.setGeometry(QtCore.QRect(70, 10, 121, 541))
        font = QtGui.QFont()
        font.setItalic(True)
        font.setKerning(False)
        self.keys_only_widget.setFont(font)
        self.keys_only_widget.setObjectName("keys_only_widget")
        self.label_2 = QtWidgets.QLabel(self.keys_only_widget)
        self.label_2.setGeometry(QtCore.QRect(0, 20, 50, 50))
        self.label_2.setMinimumSize(QtCore.QSize(50, 50))
        self.label_2.setMaximumSize(QtCore.QSize(50, 50))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/icons/resources/iStock-471629610-Converted.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.keys_only_widget)
        self.label_3.setGeometry(QtCore.QRect(40, 30, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Reem Kufi")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(False)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.layoutWidget1 = QtWidgets.QWidget(self.keys_only_widget)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 80, 111, 441))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.home_btn2 = QtWidgets.QPushButton(self.layoutWidget1)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/resources/house-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home_btn2.setIcon(icon6)
        self.home_btn2.setIconSize(QtCore.QSize(14, 14))
        self.home_btn2.setCheckable(True)
        self.home_btn2.setAutoExclusive(True)
        self.home_btn2.setObjectName("home_btn2")
        self.verticalLayout_2.addWidget(self.home_btn2)
        self.developers_btn2 = QtWidgets.QPushButton(self.layoutWidget1)
        self.developers_btn2.setIcon(icon1)
        self.developers_btn2.setIconSize(QtCore.QSize(14, 14))
        self.developers_btn2.setCheckable(True)
        self.developers_btn2.setAutoExclusive(True)
        self.developers_btn2.setObjectName("developers_btn2")
        self.verticalLayout_2.addWidget(self.developers_btn2)
        self.contact_btn2 = QtWidgets.QPushButton(self.layoutWidget1)
        self.contact_btn2.setIcon(icon2)
        self.contact_btn2.setIconSize(QtCore.QSize(14, 14))
        self.contact_btn2.setCheckable(True)
        self.contact_btn2.setAutoExclusive(True)
        self.contact_btn2.setObjectName("contact_btn2")
        self.verticalLayout_2.addWidget(self.contact_btn2)
        self.support_btn2 = QtWidgets.QPushButton(self.layoutWidget1)
        self.support_btn2.setIcon(icon3)
        self.support_btn2.setIconSize(QtCore.QSize(14, 14))
        self.support_btn2.setCheckable(True)
        self.support_btn2.setAutoExclusive(True)
        self.support_btn2.setObjectName("support_btn2")
        self.verticalLayout_2.addWidget(self.support_btn2)
        self.abtus_btn2 = QtWidgets.QPushButton(self.layoutWidget1)
        self.abtus_btn2.setIcon(icon4)
        self.abtus_btn2.setIconSize(QtCore.QSize(14, 14))
        self.abtus_btn2.setCheckable(True)
        self.abtus_btn2.setAutoExclusive(True)
        self.abtus_btn2.setObjectName("abtus_btn2")
        self.verticalLayout_2.addWidget(self.abtus_btn2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.exit_btn2 = QtWidgets.QPushButton(self.layoutWidget1)
        self.exit_btn2.setIcon(icon5)
        self.exit_btn2.setIconSize(QtCore.QSize(14, 14))
        self.exit_btn2.setCheckable(True)
        self.exit_btn2.setAutoExclusive(True)
        self.exit_btn2.setObjectName("exit_btn2")
        self.verticalLayout_2.addWidget(self.exit_btn2)
        self.main_widget = QtWidgets.QWidget(self.centralwidget)
        self.main_widget.setGeometry(QtCore.QRect(210, 0, 631, 581))
        self.main_widget.setObjectName("main_widget")
        self.widget = QtWidgets.QWidget(self.main_widget)
        self.widget.setGeometry(QtCore.QRect(0, 20, 571, 81))
        self.widget.setObjectName("widget")
        self.layoutWidget2 = QtWidgets.QWidget(self.widget)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 0, 541, 52))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sidebar_btn = QtWidgets.QPushButton(self.layoutWidget2)
        self.sidebar_btn.setMinimumSize(QtCore.QSize(50, 50))
        self.sidebar_btn.setMaximumSize(QtCore.QSize(50, 50))
        self.sidebar_btn.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/resources/sidebar2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sidebar_btn.setIcon(icon7)
        self.sidebar_btn.setIconSize(QtCore.QSize(22, 22))
        self.sidebar_btn.setCheckable(True)
        self.sidebar_btn.setAutoExclusive(False)
        self.sidebar_btn.setObjectName("sidebar_btn")
        self.horizontalLayout.addWidget(self.sidebar_btn)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.title_ensah = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.title_ensah.setFont(font)
        self.title_ensah.setObjectName("title_ensah")
        self.horizontalLayout.addWidget(self.title_ensah)
        self.stackedWidget = QtWidgets.QStackedWidget(self.main_widget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 110, 571, 411))
        self.stackedWidget.setObjectName("stackedWidget")
        
        # --- Loading pages from separate files ---
        self.home_page = HomePage()           # instance from pages/home.py
        self.developers_page = DevelopersPage()  # instance from pages/developers.py
        self.contact_page = ContactPage()       # instance from pages/contact.py
        self.support_page = SuportPage()        # instance from pages/support.py
        self.abtus_page = AbtusPage()           # instance from pages/abtus.py
        
        # Add the pages to the stacked widget in the desired order
        self.stackedWidget.addWidget(self.home_page)         # index 0
        self.stackedWidget.addWidget(self.developers_page)   # index 1
        self.stackedWidget.addWidget(self.contact_page)        # index 2
        self.stackedWidget.addWidget(self.support_page)        # index 3
        self.stackedWidget.addWidget(self.abtus_page)         # index 4
        
        # Optionally add an exit page or handle exit separately
        self.exit_page = QtWidgets.QWidget()
        exit_layout = QtWidgets.QVBoxLayout(self.exit_page)
        exit_label = QtWidgets.QLabel("Exit Page", self.exit_page)
        exit_layout.addWidget(exit_label)
        self.stackedWidget.addWidget(self.exit_page)           # index 5
        
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        # Set default page (adjust index as needed)
        self.stackedWidget.setCurrentIndex(0)

        # --- Existing connections to sync sidebar buttons ---
        self.sidebar_btn.toggled['bool'].connect(self.icons_only_widget.setVisible)
        self.sidebar_btn.toggled['bool'].connect(self.keys_only_widget.setHidden)
        self.home_btn.toggled['bool'].connect(self.home_btn2.setChecked)
        self.developers_btn.toggled['bool'].connect(self.developers_btn2.setChecked)
        self.contact_btn.toggled['bool'].connect(self.contact_btn2.setChecked)
        self.support_btn.toggled['bool'].connect(self.support_btn2.setChecked)
        self.abtus_btn.toggled['bool'].connect(self.abtus_btn2.setChecked)
        self.abtus_btn2.toggled['bool'].connect(self.abtus_btn.setChecked)
        self.support_btn2.toggled['bool'].connect(self.support_btn.setChecked)
        self.contact_btn2.toggled['bool'].connect(self.contact_btn.setChecked)
        self.developers_btn2.toggled['bool'].connect(self.developers_btn.setChecked)
        self.home_btn2.toggled['bool'].connect(self.home_btn.setChecked)

        # --- New Connections for switching stacked widget pages ---
        # Home buttons -> Home Page (index 0)
        self.home_btn.toggled['bool'].connect(lambda checked: self.stackedWidget.setCurrentIndex(0) if checked else None)
        self.home_btn2.toggled['bool'].connect(lambda checked: self.stackedWidget.setCurrentIndex(0) if checked else None)

        # Developers buttons -> Developers Page (index 1)
        self.developers_btn.toggled['bool'].connect(lambda checked: self.stackedWidget.setCurrentIndex(1) if checked else None)
        self.developers_btn2.toggled['bool'].connect(lambda checked: self.stackedWidget.setCurrentIndex(1) if checked else None)

        # Contact buttons -> Contact Page (index 2)
        self.contact_btn.toggled['bool'].connect(lambda checked: self.stackedWidget.setCurrentIndex(2) if checked else None)
        self.contact_btn2.toggled['bool'].connect(lambda checked: self.stackedWidget.setCurrentIndex(2) if checked else None)

        # Support buttons -> Support Page (index 3)
        self.support_btn.toggled['bool'].connect(lambda checked: self.stackedWidget.setCurrentIndex(3) if checked else None)
        self.support_btn2.toggled['bool'].connect(lambda checked: self.stackedWidget.setCurrentIndex(3) if checked else None)

        # Abt us buttons -> About Us Page (index 4)
        self.abtus_btn.toggled['bool'].connect(lambda checked: self.stackedWidget.setCurrentIndex(4) if checked else None)
        self.abtus_btn2.toggled['bool'].connect(lambda checked: self.stackedWidget.setCurrentIndex(4) if checked else None)

        # Exit buttons -> Exit Page (index 5)
        self.exit_btn.toggled['bool'].connect(lambda checked: self.stackedWidget.setCurrentIndex(5) if checked else None)
        self.exit_btn2.toggled['bool'].connect(lambda checked: self.stackedWidget.setCurrentIndex(5) if checked else None)
        # -----------------------------------------------------

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Sidebar"))
        self.home_btn2.setText(_translate("MainWindow", "Home"))
        self.developers_btn2.setText(_translate("MainWindow", "developers"))
        self.contact_btn2.setText(_translate("MainWindow", "contact"))
        self.support_btn2.setText(_translate("MainWindow", "support"))
        self.abtus_btn2.setText(_translate("MainWindow", "Abt us"))
        self.exit_btn2.setText(_translate("MainWindow", "EXIT"))
        self.title_ensah.setText(_translate("MainWindow", "WELCOME TO ENSA-H HOSPITAL"))


import src_icons_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
      # Load QSS file
    with open("style.qss", "r") as file:
        qss = file.read()
        app.setStyleSheet(qss)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
